# Generated by Django 4.1 on 2023-06-06 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("field", models.CharField(max_length=20)),
                ("description_text", models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("dob", models.DateTimeField()),
                ("phone", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("description_text", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="recuitment_new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("job_descrip", models.CharField(max_length=500)),
                ("job_demand", models.CharField(max_length=500)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 6, 19, 30, 52, 688604)
                    ),
                ),
                ("xxx", models.CharField(max_length=10, null=True)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.profile"
                    ),
                ),
                (
                    "recuitment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.recuitment_new",
                    ),
                ),
            ],
        ),
    ]
