# Generated by Django 4.1 on 2023-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recuitment_new",
            name="experience_demand",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recuitment_new",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
