# Generated by Django 4.1 on 2023-06-09 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 1, 34, 24, 510802)
            ),
        ),
    ]
