# Generated by Django 4.1 on 2023-06-11 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_profile_country_profile_facebook_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recuitment_new",
            old_name="company_id",
            new_name="company",
        ),
        migrations.AlterField(
            model_name="application",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 11, 22, 14, 28, 664300)
            ),
        ),
    ]
