# Generated by Django 4.1 on 2023-06-20 08:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_company_employer_alter_application_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 20, 15, 11, 52, 781370)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
