# Generated by Django 4.1 on 2023-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_recuitment_new_experience_demand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
