# Generated by Django 4.1 on 2023-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_company_phone_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
