# Generated by Django 4.1 on 2023-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
